# Generated by Django 6.0.3 on 2026-03-28 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(blank=True, db_column='FILE_NAME', null=True)),
                ('file_size', models.CharField(blank=True, db_column='FILE_SIZE', null=True)),
                ('user_id', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'POC_FILE_RESOURCE',
            },
        ),
    ]
