# Generated by Django 6.0.3 on 2026-03-28 09:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileUpload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileresource',
            name='id',
            field=models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
