# Generated by Django 6.0.3 on 2026-03-25 13:12

import authuser.model.user
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_column='USERNAME', max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, db_column='EMAIL', max_length=254)),
                ('verified_email', models.BooleanField(db_column='VERIFIED_EMAIL', default=False)),
                ('is_agreement', models.BooleanField(db_column='IS_AGREEMENT', default=False)),
                ('is_user', models.BooleanField(db_column='IS_USER', default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'POC_USER',
            },
            managers=[
                ('object', authuser.model.user.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='FIRST_NAME', max_length=255)),
                ('last_name', models.CharField(blank=True, db_column='LAST_NAME', max_length=255, null=True)),
                ('user', models.OneToOneField(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'POC_USER_DETAIL',
            },
        ),
    ]
