# Generated by Django 6.0.3 on 2026-03-26 13:47

import authuser.model.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authuser.model.user.CustomUserManager()),
            ],
        ),
    ]
