# Generated by Django 6.0.3 on 2026-03-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verified_email',
        ),
    ]
