# Generated by Django 6.0.3 on 2026-03-27 06:07

import authuser.model.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0006_remove_user_verified_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', authuser.model.user.CustomUserManager()),
            ],
        ),
    ]
