# Generated by Django 6.0.3 on 2026-03-27 06:10

import authuser.model.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authuser.model.user.CustomUserManager()),
            ],
        ),
    ]
